#pragma once
namespace lightHostModern::ui {
inline winrt::hstring HoverHelp::explanation(winrt::hstring const& label) const {
    if(label==L"Input mode"||label==catalog.translatedSource(L"Input mode"))return catalog.text("audio.inputMode.tooltip",L"Keep inputs separate in Stereo or combine them in Mono.");
    if(label==L"Output mode"||label==catalog.translatedSource(L"Output mode"))return catalog.text("audio.mainOutputMode.tooltip",L"Keep the main outputs separate in Stereo or mix them in Mono. Other outputs are unchanged.");
    if(label==L"Channel selection"||label==catalog.translatedSource(L"Channel selection"))return catalog.text("audio.channelSelection.tooltip",L"Change how channels are displayed without changing existing wires.");
    struct Help {const wchar_t* label;const char* key;const wchar_t* fallback;};
    static constexpr Help entries[]={
        {L"Audio backend","help.option.000",L"Choose the driver system used to send and receive audio."},
        {L"Input device","help.option.001",L"Choose the device that supplies audio to the app."},
        {L"Output device","help.option.002",L"Choose the device that plays the processed audio."},
        {L"Sample rate","help.option.003",L"Choose how many audio samples are processed each second."},
        {L"Buffer size","help.option.004",L"Smaller buffers reduce delay but require more processing power."},
        {L"Enable this audio backend","help.option.005",L"Allow the app to use this driver system and its enabled devices."},
        {L"Active audio channel","help.option.006",L"Choose whether this device channel participates in audio processing."},
        {L"Plugin audio format","help.option.007",L"Choose a format supported by this plugin. Related inputs and outputs may change together."},
        {L"Configure plugin channels","help.option.008",L"Choose the input and output formats supported by this plugin."},
        {L"Input channels","help.option.009",L"Configure which input channels are visible and how they are grouped."},
        {L"Output channels","help.option.010",L"Configure which output channels are visible and how they are grouped."},
        {L"Enable channels","help.option.011",L"Show channels that are currently disabled or hidden."},
        {L"Disable channels","help.option.012",L"Choose currently enabled channels to disable or hide."},
        {L"Pairs","help.option.013",L"Show consecutive channels together. Existing wires keep their current connections."},
        {L"Individual","help.option.014",L"Show each channel separately. Existing wires keep their current connections."},
        {L"Name","help.option.015",L"Choose the name shown in the app."},
        {L"Custom name","help.option.016",L"Choose a display name without changing the original plugin file."},
        {L"Description (optional)","help.option.017",L"Add a short note to help identify this profile."},
        {L"Save current audio settings","help.option.018",L"Include the devices, audio format and channel settings currently selected in the app."},
        {L"Search profiles","help.option.019",L"Find saved profiles by name."},
        {L"Search running plugins","help.option.020",L"Find a plugin instance currently in your setup."},
        {L"Search installed plugins","help.option.021",L"Filter the available plugins by name or manufacturer."},
        {L"Find an element in the chain","help.option.022",L"Find and highlight a plugin or element on the canvas."},
        {L"Sort","help.option.023",L"Choose the display order and optional grouping of plugins."},
        {L"Group by manufacturer","help.option.024",L"Group plugins under the name of their manufacturer."},
        {L"Add plugin","help.option.025",L"Select installed plugins to add to this chain."},
        {L"Add mixer","help.option.026",L"Add an element that combines audio from several inputs."},
        {L"Scan for plugins","help.option.027",L"Search the selected folders for new or updated plugins."},
        {L"Scan folder","help.option.028",L"Enter a folder where the app should search for plugins."},
        {L"Browse folder","help.option.029",L"Choose a folder on your computer."},
        {L"Save path","help.option.030",L"Include this folder in future plugin scans."},
        {L"Remove path","help.option.031",L"Stop scanning this folder. Its files are kept."},
        {L"Mute output","help.option.032",L"Silence the final output while plugins keep processing."},
        {L"Unmute output","help.option.033",L"Restore sound at the final output."},
        {L"Bypass chain","help.option.034",L"Listen to the original audio without plugin effects."},
        {L"Disable bypass chain","help.option.035",L"Use the plugin effects again."},
        {L"Bypass","help.option.036",L"Temporarily skip this plugin effect without removing it."},
        {L"Enable","help.option.037",L"Use this plugin effect again."},
        {L"Open editor","help.option.038",L"Open the plugin window to adjust its own settings."},
        {L"Retry loading","help.option.039",L"Try loading this plugin again after an error."},
        {L"Duplicate","help.option.040",L"Add another instance with the same current settings."},
        {L"Rename","help.option.041",L"Change the display name or restore the original name."},
        {L"Rename plugin","help.option.042",L"Change the display name or restore the original plugin name."},
        {L"Rename instance","help.option.043",L"Change the name of this running instance only."},
        {L"Rename channel","help.option.044",L"Change the channel name or restore its original name."},
        {L"Rename device","help.option.045",L"Change the displayed device name without changing its Windows name."},
        {L"Restore original name","help.option.046",L"Remove the custom name and use the original name again."},
        {L"Card color","help.option.047",L"Choose the color used to identify this card."},
        {L"Channel color","help.option.048",L"Choose a channel color. Connected wires use this color at that end."},
        {L"Horizontal channels","help.option.049",L"Place channel connectors side by side."},
        {L"Vertical channels","help.option.050",L"Place channel connectors in a vertical list."},
        {L"Arrange layers","help.option.051",L"Choose which overlapping cards appear in front."},
        {L"Bring to front","help.option.052",L"Place this card in front of all other cards."},
        {L"Bring forward","help.option.053",L"Move this card one layer forward."},
        {L"Send backward","help.option.054",L"Move this card one layer backward."},
        {L"Send to back","help.option.055",L"Place this card behind all other cards."},
        {L"Disconnect input wires","help.option.056",L"Remove wires arriving at the selected elements."},
        {L"Disconnect output wires","help.option.057",L"Remove wires leaving the selected elements."},
        {L"Disconnect","help.option.058",L"Remove this wire without removing either element."},
        {L"Organize","help.option.059",L"Arrange the elements from input to output. Audio connections are kept."},
        {L"Show offscreen elements","help.option.060",L"Show arrows pointing to elements outside the visible canvas."},
        {L"Fit to screen","help.option.061",L"Adjust the view to show all elements."},
        {L"Zoom in","help.option.062",L"Enlarge the canvas view."},
        {L"Zoom out","help.option.063",L"Reduce the canvas view to see more elements."},
        {L"Undo","help.option.064",L"Undo the last chain change."},
        {L"Redo","help.option.065",L"Reapply the last change that was undone."},
        {L"Add new input channel","help.option.066",L"Add another stereo input pair to this mixer."},
        {L"Add new output channel","help.option.067",L"Add another stereo output pair to this mixer."},
        {L"Delete channel pair","help.option.068",L"Remove both channels of this mixer pair and their wires."},
        {L"Mute","help.option.069",L"Silence this mixer input pair."},
        {L"Controls Left and Right together.","help.option.070",L"Adjust the volume of both channels in this mixer input pair."},
        {L"Run in a separate process (experimental)","help.option.071",L"Run this plugin in a worker process to help contain plugin crashes."},
        {L"Run inside the host","help.option.072",L"Run this plugin directly in the main audio process."},
        {L"Default color","help.option.073",L"Remove this custom color and use the app default."},
        {L"Save custom color","help.option.074",L"Save the chosen color in your palette for later use."},
        {L"Delete color","help.option.075",L"Remove this color from the saved palette. Existing cards keep their colors."},
        {L"Color","help.option.076",L"Choose the color and its transparency."},
        {L"Activate","help.option.077",L"Load this saved profile and replace the current setup."},
        {L"Save current settings as a new profile","help.option.078",L"Save the current plugin setup in a new profile."},
        {L"Remove","help.option.079",L"Remove this element and its connections from the current setup."},
        {L"Remove from database","help.option.080",L"Remove this plugin from the app database. Its file is kept."},
        {L"Plugin details","help.option.081",L"View the plugin identity, format, version and file location."},
        {L"Open folder","help.option.082",L"Open the folder containing this plugin."},
        {L"Insert input channel","help.option.083",L"Choose the channel that receives audio from the existing wire."},
        {L"Insert output channel","help.option.084",L"Choose the channel that sends audio to the existing destination."},
        {L"Enabled device","help.option.085",L"Allow the app to use this audio device."},
    };
    for(const auto& entry:entries)if(label==entry.label||label==catalog.translatedSource(entry.label))return catalog.text(entry.key,entry.fallback);
    return {};
}
}
